### ISSUE TITLE
Maintainance of Federation Daboard Plugin

### ISSUE THREAD

**Issue by zakuru** [module-federation/federation-dashboard#458]
Hi @ScriptedAlchemy 

Is this the correct repository for this NPM: https://www.npmjs.com/package/@module-federation/dashboard-plugin?activeTab=readme ?

The github repo mentions version 2.7.1 but in npmjs.com I see 2.7.2

Asking cause want to push for a fix

**Comment by steven-prybylynskyi** [comment]
On a related note, is the Dashboard plugin free to use or requires a Medusa subscription?

**Comment by ScriptedAlchemy** [comment]
Dashboard plugin will emit json ingested by Medusa, so you can use its json if you have your infra to send it to

**Comment by zakuru** [comment]
Closing as I can see the versions in sync now
Thanks   @ScriptedAlchemy
